go

use Budget

CREATE TABLE ACCOUNTS (
ID smallint PRIMARY KEY IDENTITY (1,1) NOT NULL,
ACCOUNT_NAME nvarchar(255) NOT NULL,
ACCOUNT_NUMBER nvarchar (255) NOT NULL,
BALANCE dec (10,2) DEFAULT 0 NOT NULL,
BANK nvarchar(255) NOT NULL,
CURRENCY nchar(3) NOT NULL
);