GO
USE Budget
GO
IF OBJECT_ID('EXPENSE_CATEG_AGG_MM') IS NOT NULL
	DROP TABLE EXPENSE_CATEG_AGG_MM;
GO

CREATE TABLE EXPENSE_CATEG_AGG_MM (
BANK nvarchar(50) NOT NULL,
CARD_NAME nvarchar (50) NOT NULL,
CALYEAR nvarchar(4) NOT NULL,
CALMONTH nvarchar(6) NOT NULL,
BILL_AMOUNT dec(10,2) NOT NULL,
BILL_AMOUNT_BYN dec(10,2) NOT NULL,
BILL_CURRENCY nvarchar(10) NOT NULL,
TXN_CATEGORY nvarchar(255) NOT NULL,
MCC nvarchar(4) NULL,
AMOUNT_THRESHOLD dec(10,2) NULL
);
